Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,6 +12,10 @@ jobs:
     steps:
     - uses: actions/checkout@v4
     
+    - name: Debug - List Files
+      run: ls -R
+
+    
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
@@ -24,5 +28,8 @@ jobs:
         gradle-version: '8.4'
         
     - name: Build with Gradle
-      run: gradle build --no-daemon
-      working-directory: android
+      run: |
+        ls -la
+        cd android || echo "Android directory not found!"
+        ls -la
+        gradle build --no-daemon
